language: node_js
node_js: 
  - "10"
before_install:
  - cd packages/react-scripts
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_API_TOKEN"
  skip_cleanup: true
  on:
    branch: example-dev